--create type [SqlT].[DatabaseDescription] as table
--(
--    DatabaseName sysname not null,
--	DatabaseVersion nvarchar (25) not null,
--	IsModel bit not null,
--    ModelName nvarchar(128),
--    Documentation nvarchar(250) null
--)
--GO
