CREATE TABLE SqlTestResult.[SchemaTable]
(
	SurrogateKey int not null constraint DF_SchemaTable default (next value for [SqlTestResult].[SchemaTableSeq]),
	ColumnName sysname not null,
	ColumnOrdinal int not null,
	ColumnSize int not null,
	NumericPrecision tinyint not null,
	NumericScale tinyint not null,
	IsUnique bit not null,
	IsKey bit null,
	BaseServerName sysname null,
	BaseCatalogName sysname null,
	BaseColumnName sysname not null,
	BaseSchemaName sysname null,
	BaseTableName sysname null,
	DataType nvarchar(128) not null,
	AllowDBNull bit not null,
	ProviderType int not null,
	IsAliased bit null,
	IsExpression bit null,
	IsIdentity bit not null,
	IsAutoIncrement bit not null,
	IsRowVersion bit not null,
	IsHidden bit null,
	IsLong bit not null,
	IsReadOnly bit not null,
	ProviderSpecificDataType nvarchar(128) not null,
	DataTypeName sysname not null,
	XmlSchemaCollectionDatabase sysname null,
	XmlSchemaCollectionOwningSchema sysname null,
	XmlSchemaCollectionCollectionName sysname null,
	UdtAssemblyQualifiedName nvarchar(256) null,
	NonVersionedProviderType int not null,
	IsColumnSet bit not null,
	DbCreateUser nvarchar(75) not null constraint DF_SchemaTable_CreateUser default(suser_sname()),
	DbCreateTime datetime2(7) not null constraint DF_SchemaTable_CreateTime default(sysdatetime())
)

