CREATE type [systems].[servers_record] as table
(
	[systems_server_name] sysname not null,
	[server_id] [int] NOT NULL,
	[name] [sysname] NOT NULL,
	[product] [sysname] NOT NULL,
	[provider] [sysname] NOT NULL,
	[data_source] [nvarchar](4000) NULL,
	[location] [nvarchar](4000) NULL,
	[provider_string] [nvarchar](4000) NULL,
	[catalog] [sysname] NULL,
	[connect_timeout] [int] NULL,
	[query_timeout] [int] NULL,
	[is_linked] [bit] NOT NULL,
	[is_remote_login_enabled] [bit] NOT NULL,
	[is_rpc_out_enabled] [bit] NOT NULL,
	[is_data_access_enabled] [bit] NOT NULL,
	[is_collation_compatible] [bit] NOT NULL,
	[uses_remote_collation] [bit] NOT NULL,
	[collation_name] [sysname] NULL,
	[lazy_schema_validation] [bit] NOT NULL,
	[is_system] [bit] NOT NULL,
	[is_publisher] [bit] NOT NULL,
	[is_subscriber] [bit] NULL,
	[is_distributor] [bit] NULL,
	[is_nonsql_subscriber] [bit] NULL,
	[is_remote_proc_transaction_promotion_enabled] [bit] NULL,
	[modify_date] [datetime] NOT NULL
)
